dist: xenial
addons:
  apt:
    packages:
      - docker
services:
  - docker
language: python
python:
  - '3.6'
  - '3.7'
stages:
- linting
- test
- deploy

jobs:
  include:
    - stage: deploy
      python: '3.6'
      env:
      install: pip install -U setuptools setuptools_scm wheel
      script: skip
      deploy:
        provider: pypi
        user: ronny
        password:
          secure: "Z5d5OHjmr20rliaSFQHBnTJ1ZnesODsfY3IdpSeucuxp6+qhd22niCslbTLzkM9lKv94U1yZ50aVYTIb6WmrH6dPcxDJxBPm30ezVOHtbkoQyKL/+Xt961lljWJTqlv+DI1qz7VY86qx53HJw94zpK1CF5bA8+ZSivzcx4MVYpxyb/0mYRJh75/zRHJsiRgTkC9rXcZ8rEzuRdx7/p1AIpGWp0U67QzMvtOWIds4uNxisaRgxGNJDk63301O8o46oehNI7UR+H6SwKYHyFVqwS5dGUjfqXcnkaOkGjnYOgoqVZXM/sfqpC88FChELFoYqGR42KARGnAqcwyvDkra7uni7Vhg2SpbJFSQw3DCm+h3Zmme3zthIxiqdFFua0bIH0+LISodkOap1XznmYSR4Rior1LiCN0KQ6hGlvDoPSHfnHKFWWrvLeQvwCzRt1mSyAejybQ7fdthOcEo0DgFFF9LFicLmaLD+r6p8EfV/c7FoKY5xtfn5weBzRJHwFQS0gbrcPvCIhoPDLc1dsjh1Bfh99PwwV37zlO3ncfJ7RWK5/peAEyqG/cmWykjMHOfAF7tlsK856o+OCH+e95ppDvvEX7DIh+XSgwCatlpnqxHnyW1J/0F2olBPT4JrA6UYKhJP5cWWthKDdrijxW5dOel0lgeNqZ3Hk6CeUveTmo="
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        on:
          tags: true
    - stage: linting
      python: '3.6'
      env:
      install:
      - pip install pre-commit
      - pre-commit install-hooks
      script:
      - pre-commit run --all-files
install:
  - pip install -U setuptools pip
  - pip install -U -e . pytest docker requests
  - docker pull cfmeqe/webdriver-wharf
script:
  - pytest
cache:
  directories:
    #- $HOME/.cache/pip
    - $HOME/.cache/pre-commit
